# Generated by Django 4.0.5 on 2022-07-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_By', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('discription', models.TextField()),
                ('like', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
